saml.sp.entity-id=http://localhost:8080/saml/sp
saml.sp.acs-url=http://localhost:8080/saml/acs
saml.sp.base-url=http://localhost:8080
saml.idp.sso-url=https://keycloak.local:8443/realms/iam/protocol/saml
saml.idp.signing-cert=
