spring.datasource.url=jdbc:postgresql://localhost:5432/iam_engine
spring.datasource.username=iam_user
spring.datasource.password=${POSTGRES_PASSWORD:iam_password_dev}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=${REDIS_PASSWORD:redis_password_dev}

spring.flyway.enabled=false

server.port=8080
iam.issuer=http://localhost:8080

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

logging.level.com.iam=DEBUG