spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/iam_engine
    username: iam_user
    password: iam_password
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
